#!/bin/bash
# EvoAgent - Webhook & GitHub Integration

EVO_DIR="$HOME/.openclaw/evo"
WEBHOOKS_DIR="$EVO_DIR/webhooks"

mkdir -p "$WEBHOOKS_DIR"

CMD=$1
shift

case $CMD in
  webhook)
    # evo webhook add <name> <url>
    # evo webhook list
    # evo webhook test <name>
    # evo webhook remove <name>
    
    ACTION=$1
    NAME=$2
    URL=$3
    
    case $ACTION in
      add)
        if [ -n "$NAME" ] && [ -n "$URL" ]; then
          echo "{\"name\": \"$NAME\", \"url\": \"$URL\", \"enabled\": true}" > "$WEBHOOKS_DIR/$NAME.json"
          echo "✅ Webhook added: $NAME -> $URL"
        else
          echo "Usage: evo webhook add <name> <url>"
        fi
        ;;
        
      list)
        echo "📡 Configured Webhooks:"
        for f in "$WEBHOOKS_DIR"/*.json; do
          if [ -f "$f" ]; then
            NAME=$(basename "$f" .json)
            URL=$(python3 -c "import json; print(json.load(open('$f')).get('url','N/A'))" 2>/dev/null)
            ENABLED=$(python3 -c "import json; print(json.load(open('$f')).get('enabled',False))" 2>/dev/null)
            echo "• $NAME: $URL [$( [ "$ENABLED" = "True" ] && echo ON || echo OFF )]"
          fi
        done
        ;;
        
      test)
        if [ -f "$WEBHOOKS_DIR/$NAME.json" ]; then
          URL=$(python3 -c "import json; print(json.load(open('$WEBHOOKS_DIR/$NAME.json')).get('url'))" 2>/dev/null)
          echo "🧪 Testing webhook: $NAME"
          curl -s -X POST "$URL" -H "Content-Type: application/json" -d '{"test": true, "source": "EvoAgent"}' || echo "❌ Webhook test failed"
        else
          echo "❌ Webhook not found: $NAME"
        fi
        ;;
        
      remove|delete)
        rm "$WEBHOOKS_DIR/$NAME.json" 2>/dev/null
        echo "✅ Webhook removed: $NAME"
        ;;
        
      *)
        echo "📡 Webhook Commands:"
        echo "  evo webhook add <name> <url>   - 新增 webhook"
        echo "  evo webhook list               - 列出所有 webhook"
        echo "  evo webhook test <name>       - 測試 webhook"
        echo "  evo webhook remove <name>     - 刪除 webhook"
        ;;
    esac
    ;;
    
  github)
    # evo github <experience_id>
    # Generate a shareable GitHub Gist
    
    ID=$1
    
    if [ -d "$EVO_DIR/experiences/$ID" ]; then
      EVENT="$EVO_DIR/experiences/$ID/event.json"
      GENE="$EVO_DIR/genes/${ID}.md"
      CAPSULE="$EVO_DIR/capsules/${ID}.md"
      
      # Generate markdown for sharing
      cat > "/tmp/evo_${ID}.md" << EOF
# EvoAgent Experience: $ID

## Metadata
- **Type**: $(python3 -c "import json; print(json.load(open('$EVENT')).get('task_type','N/A'))" 2>/dev/null)
- **Quality**: $(python3 -c "import json; print(json.load(open('$EVENT')).get('quality_score','N/A'))" 2>/dev/null)/10
- **Outcome**: $(python3 -c "import json; print(json.load(open('$EVENT')).get('outcome','N/A'))" 2>/dev/null)
- **Tags**: $(python3 -c "import json; print(json.load(open('$EVENT')).get('tags','N/A'))" 2>/dev/null)

## Problem
$(python3 -c "import json; print(json.load(open('$EVENT')).get('problem','N/A'))" 2>/dev/null)

## Solution
$(python3 -c "import json; print(json.load(open('$EVENT')).get('solution','N/A'))" 2>/dev/null)

---
*Generated by EvoAgent - AI Experience Evolution System*
EOF
      
      echo "✅ Generated shareable markdown: /tmp/evo_${ID}.md"
      echo ""
      cat "/tmp/evo_${ID}.md"
      echo ""
      echo "📤 要 post 上 GitHub Gist 既話，可以 copy 以上內容"
    else
      echo "❌ Experience not found: $ID"
    fi
    ;;
    
  share)
    # evo share <experience_id> - generate shareable link (future: could use pastebin, etc)
    ID=$1
    
    if [ -d "$EVO_DIR/experiences/$ID" ]; then
      # For now, just show the shareable content
      ~/.openclaw/workspace/skills/evo-agent/evo.sh github "$ID"
    else
      echo "❌ Experience not found: $ID"
    fi
    ;;
    
  auto-push)
    # evo auto-push enable/disable
    # Automatically push to configured webhook on new record
    
    ACTION=$1
    
    if [ "$ACTION" = "enable" ]; then
      echo '{"auto_push": true}' > "$EVO_DIR/.auto_push"
      echo "✅ Auto-push enabled"
    elif [ "$ACTION" = "disable" ]; then
      echo '{"auto_push": false}' > "$EVO_DIR/.auto_push"
      echo "✅ Auto-push disabled"
    else
      if [ -f "$EVO_DIR/.auto_push" ]; then
        STATUS=$(python3 -c "import json; print(json.load(open('$EVO_DIR/.auto_push')).get('auto_push',False))" 2>/dev/null)
        echo "Auto-push: $( [ "$STATUS" = "True" ] && echo enabled || echo disabled )"
      else
        echo "Auto-push: disabled"
      fi
    fi
    ;;
    
  *)
    echo "📤 Share & Webhook Commands:"
    echo "  evo webhook add <name> <url>    - 新增 webhook"
    echo "  evo webhook list                 - 列出 webhooks"
    echo "  evo webhook test <name>         - 測試 webhook"
    echo "  evo webhook remove <name>       - 刪除 webhook"
    echo ""
    echo "  evo github <id>                 - 生成 GitHub Gist 格式"
    echo "  evo share <id>                  - 生成可分享既內容"
    echo ""
    echo "  evo auto-push [enable|disable]  - 自動 push 到 webhook"
    ;;
esac
